In [ ]:
# 构建文本特征

## 1 N-gram

In [1]:
from nltk import ngrams
sentence = 'this is a foo bar sentences and i want to ngramize it'
n = 4 # you can give 4, 5, 1 or any number less than sentences length
ngramsres = ngrams(sentence.split(), n)
for grams in ngramsres:
    print(grams)

('this', 'is', 'a', 'foo')
('is', 'a', 'foo', 'bar')
('a', 'foo', 'bar', 'sentences')
('foo', 'bar', 'sentences', 'and')
('bar', 'sentences', 'and', 'i')
('sentences', 'and', 'i', 'want')
('and', 'i', 'want', 'to')
('i', 'want', 'to', 'ngramize')
('want', 'to', 'ngramize', 'it')


## 2 bagofwords词袋

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

# analyzer是构建词袋模型，所使的训练集文本
ngram_vectorizer = CountVectorizer(analyzer='char_wb', ngram_range=(2, 2), min_df=1)

counts = ngram_vectorizer.fit_transform(['words', 'wprds'])
# this check weather the given word character is present in the above teo word which are documents here.
ngram_vectorizer.get_feature_names() == ([' w', 'ds', 'or', 'pr', 'rd', 's ', 'wo', 'wp'])
print(counts.toarray().astype(int))

[[1 1 1 0 1 1 1 0]
 [1 1 0 1 1 1 0 1]]


In [4]:
counts.toarray()

array([[1, 1, 1, 0, 1, 1, 1, 0],
       [1, 1, 0, 1, 1, 1, 0, 1]], dtype=int64)

# 3 one-hot编码

X[['country']]返回的是dataframe;  

X['country']返回的是seriese

In [14]:
import pandas as pd
from sklearn.feature_extraction import DictVectorizer

X = pd.DataFrame({'income': [100000,110000,90000,30000,14000,50000],
                  'country':['US', 'CAN', 'US', 'CAN', 'MEX', 'US'],
                  'race':['White', 'Black', 'Latino', 'White', 'White', 'Black']})
v = DictVectorizer()
X_qual = v.fit_transform(X[['country']].to_dict('records'))
print(v.vocabulary_)
print( X_qual.toarray())

{'country=US': 2, 'country=CAN': 0, 'country=MEX': 1}
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 4 doc2vec模型

In [1]:
import logging
import gensim.models as g
import codecs

In [3]:
# enable logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

## 4.1 模型参数 

In [2]:
# doc2vec parameters
vector_size = 300
window_size = 15
min_count = 1
sampling_threshold = 1e-5
negative_size = 5
train_epoch = 100
dm = 0  # 0 = dbow; 1 = dmpv
worker_count = 1  # number of parallel processes

## 4.2 语料

In [4]:
# 该语料中，词汇用空格保存
train_corpus = "/home/zt/Documents/Data/NLTK/doc2vecdata/train_docs.txt"

In [5]:
# train doc2vec model
docs = g.doc2vec.TaggedLineDocument(train_corpus)
model = g.Doc2Vec(docs, size=vector_size, window=window_size, min_count=min_count, sample=sampling_threshold,
                  workers=worker_count, hs=0, dm=dm, negative=negative_size, dbow_words=1, dm_concat=1,
                  iter=train_epoch)


/home/zt/anaconda3/lib/python3.6/site-packages/gensim/models/doc2vec.py:362: UserWarning: The parameter `iter` is deprecated, will be removed in 4.0.0, use `epochs` instead.
  warnings.warn("The parameter `iter` is deprecated, will be removed in 4.0.0, use `epochs` instead.")
/home/zt/anaconda3/lib/python3.6/site-packages/gensim/models/doc2vec.py:366: UserWarning: The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.
  warnings.warn("The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.")
2018-03-18 20:03:51,847 : INFO : collecting all words and their counts
2018-03-18 20:03:51,851 : INFO : PROGRESS: at example #0, processed 0 words (0/s), 0 word types, 0 tags
2018-03-18 20:03:51,878 : INFO : collected 11097 word types and 1000 unique tags from a corpus of 1000 examples and 84408 words
2018-03-18 20:03:51,879 : INFO : Loading a fresh vocabulary
2018-03-18 20:03:51,897 : INFO : min_count=1 retains 11097 unique words (

2018-03-18 20:04:06,422 : INFO : worker thread finished; awaiting finish of 0 more threads
2018-03-18 20:04:06,422 : INFO : EPOCH - 30 : training on 84408 raw words (23625 effective words) took 0.5s, 49296 effective words/s
2018-03-18 20:04:06,899 : INFO : worker thread finished; awaiting finish of 0 more threads
2018-03-18 20:04:06,899 : INFO : EPOCH - 31 : training on 84408 raw words (23690 effective words) took 0.5s, 49727 effective words/s
2018-03-18 20:04:07,381 : INFO : worker thread finished; awaiting finish of 0 more threads
2018-03-18 20:04:07,381 : INFO : EPOCH - 32 : training on 84408 raw words (23772 effective words) took 0.5s, 49390 effective words/s
2018-03-18 20:04:07,853 : INFO : worker thread finished; awaiting finish of 0 more threads
2018-03-18 20:04:07,853 : INFO : EPOCH - 33 : training on 84408 raw words (23742 effective words) took 0.5s, 50390 effective words/s
2018-03-18 20:04:08,319 : INFO : worker thread finished; awaiting finish of 0 more threads
2018-03-18 20

2018-03-18 20:04:23,732 : INFO : worker thread finished; awaiting finish of 0 more threads
2018-03-18 20:04:23,733 : INFO : EPOCH - 67 : training on 84408 raw words (23622 effective words) took 0.5s, 52006 effective words/s
2018-03-18 20:04:24,189 : INFO : worker thread finished; awaiting finish of 0 more threads
2018-03-18 20:04:24,189 : INFO : EPOCH - 68 : training on 84408 raw words (23583 effective words) took 0.5s, 51775 effective words/s
2018-03-18 20:04:24,670 : INFO : worker thread finished; awaiting finish of 0 more threads
2018-03-18 20:04:24,671 : INFO : EPOCH - 69 : training on 84408 raw words (23776 effective words) took 0.5s, 49487 effective words/s
2018-03-18 20:04:25,136 : INFO : worker thread finished; awaiting finish of 0 more threads
2018-03-18 20:04:25,137 : INFO : EPOCH - 70 : training on 84408 raw words (23846 effective words) took 0.5s, 51337 effective words/s
2018-03-18 20:04:25,611 : INFO : worker thread finished; awaiting finish of 0 more threads
2018-03-18 20

In [ ]:
## 4.3 保存模型

In [6]:
saved_path = "doc2vec_model.bin"
model.save(saved_path)

2018-03-18 20:07:26,626 : INFO : saving Doc2Vec object under doc2vec_model.bin, separately None
2018-03-18 20:07:26,827 : INFO : saved doc2vec_model.bin


In [ ]:
## 4.4 预测

In [8]:
#parameters
model="doc2vec_model.bin"
test_docs="/home/zt/Documents/Data/NLTK/doc2vecdata/test_docs.txt"
output_file="test_vectors.txt"

#inference hyper-parameters
start_alpha=0.01
infer_epoch=1000

#load model
m = g.Doc2Vec.load(model)
print(m.wv.most_similar(positive=['family', 'dog']))
test_docs = [ x.strip().split() for x in codecs.open(test_docs, "r", "utf-8").readlines() ]

#infer test vectors
output = open(output_file, "w")
for d in test_docs:
    output.write( " ".join([str(x) for x in m.infer_vector(d, alpha=start_alpha, steps=infer_epoch)]) + "\n" )
output.flush()
output.close()

2018-03-18 20:12:18,761 : INFO : loading Doc2Vec object from doc2vec_model.bin
2018-03-18 20:12:18,938 : INFO : loading vocabulary recursively from doc2vec_model.bin.vocabulary.* with mmap=None
2018-03-18 20:12:18,939 : INFO : loading trainables recursively from doc2vec_model.bin.trainables.* with mmap=None
2018-03-18 20:12:18,939 : INFO : loading wv recursively from doc2vec_model.bin.wv.* with mmap=None
2018-03-18 20:12:18,939 : INFO : loading docvecs recursively from doc2vec_model.bin.docvecs.* with mmap=None
2018-03-18 20:12:18,940 : INFO : loaded doc2vec_model.bin
2018-03-18 20:12:18,951 : INFO : precomputing L2-norms of word weight vectors


[('peach', 0.7730699777603149), ('clingstone', 0.772639811038971), ('harp', 0.7716166973114014), ('bag', 0.7704375982284546), ('harmonica', 0.7704144716262817), ('tow', 0.7691656351089478), ('burlap', 0.7691220045089722), ('plum', 0.7690191268920898), ('dragonfly', 0.768700897693634), ('irons', 0.7677907347679138)]
